
show-work-entry:
  path: /api/work-entry/{uuid}/show
  methods: get
  controller: App\WorkEntry\Infrastructure\Controllers\WorkEntryGetController::show

show-all-work-entry-by-user:
  path: /api/work-entry/{uuid}/show-all-by-user
  methods: get
  controller: App\WorkEntry\Infrastructure\Controllers\WorkEntryGetController::showAllWorksEntriesByUserUuid

show-all-work-entrys:
  path: /api/work-entry/show-all
  methods: get
  controller: App\WorkEntry\Infrastructure\Controllers\WorkEntryGetController::showAll

create-work-entry:
  path: /api/work-entry/create
  methods: post
  controller: App\WorkEntry\Infrastructure\Controllers\WorkEntryPostController::create

signing-work-entry:
  path: /api/work-entry/{uuid}/signing
  methods: post
  controller: App\WorkEntry\Infrastructure\Controllers\WorkEntryPostController::signing

update-work-entry:
  path: /api/work-entry/{uuid}/update
  methods: put
  controller: App\WorkEntry\Infrastructure\Controllers\WorkEntryPutController::update

delete-work-entry:
  path: /api/work-entry/{uuid}/delete
  methods: delete
  controller: App\WorkEntry\Infrastructure\Controllers\WorkEntryDeleteController::delete